name: Powershell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: run powershell
        shell: PowerShell -NoProfile -Command "& '{0}'"
        run: |
          echo $Env:Path
