name: Powershell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: run powershell
      shell: powershell
      run: |-
        echo $Env:Path
        
